### ISSUE TITLE
Multiple Validation

### ISSUE THREAD

**Issue by brad-decker** [amoffat/bootstrap-application-wizard#79]
Is there something i'm doing wrong in my setup? I'm setting data-validate="methodname" on my input and when it calls it that method calls one of several reusable functions i've made for validation. one of those methods is validateRequired, which returns .status=false if there is no value assigned. So if i submit something with no value first the wizard pops up the message for required value ...

if i then change that value to one that will cause one of the other validation methods to fail, say the "no space" validation, it will prevent the card from moving to the next step but the popover message does not change to the new message.

**Comment by pvegetah** [comment]
I have a question what was the class name when using a search box in drop down in Service Selection. I just wonder about the search box inside the drop down.
